-- Enable Row Level Security on all app-owned public tables.
--
-- This app talks to Postgres directly via server-side pg connections rather than
-- Supabase PostgREST. Enabling RLS here blocks unintended Data API exposure while
-- preserving backend-owned access patterns.

ALTER TABLE IF EXISTS users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scholarship_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scholarship_cycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS program_role_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scholarship_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS field_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS field_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS view_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS config_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS view_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS section_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_cycle_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS program_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS scholarship_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS intake_forms ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS intake_form_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS intake_form_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS intake_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS intake_submission_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS intake_rate_limit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS reviewer_row_files ENABLE ROW LEVEL SECURITY;
